spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username : sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true



jwt:
  secret: 1cfa3257f16562efc93db8582ad035d856607d1b9e9cf03d1ad9f75fdaf3d1e9